Sign in
wolox-training/jz-express-js pull request #7
Opened 2018-11-15 16:31 UTC by jxczz2

## Summary

+ signIn is added
+ validations signIn is added
+ Test signIn is added 

## Known Issues

No problem.

## Trello Card

https://trello.com/c/xihe253w

2018-11-15 17:58 UTC, picollomartin requested changes
Same as before, compare with original branch not with master

2018-11-16 12:49 UTC, picollomartin requested changes
Check little typos in code, like acces or sesion (if you want, install a [spell checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) for vs-code)

2018-11-16 12:49 UTC, mpicollo-wolox commented on app/controllers/users.js
> +const giveToken = req => {
Make logic for tokens as a service

2018-11-16 12:49 UTC, mpicollo-wolox commented on app/controllers/users.js
> +          .cookie('accesToken', token)
Use a header for return token, `authorization` is normally used (make this a config variable)

2018-11-16 12:49 UTC, mpicollo-wolox commented on app/controllers/users.js
> +          .send(`x-access-token ${token}`)
This is unnecessary

2018-11-16 12:49 UTC, mpicollo-wolox commented on app/models/user.js
> +        email
Make a generic condition here

2018-11-16 12:49 UTC, mpicollo-wolox commented on app/routes.js
> +  app.post('/users/sessions/', signInMiddleware.checkValidations, userController.sesion);
Remove trailing `/`

2018-11-16 12:49 UTC, mpicollo-wolox commented on app/routes.js
> +  app.post('/users/sessions/', signInMiddleware.checkValidations, userController.sesion);
Check typo in sesion

2018-11-16 12:49 UTC, mpicollo-wolox commented on app/middlewares/signInValidations.js
> +exports.checkValidations = (req, res, next) => {
Do you need an entire file for this ?, also we talk about a generic middleware for validators (not a function for each validation)

2018-11-16 14:05 UTC, jxczz2 commented on app/controllers/users.js
> +          .send(`x-access-token ${token}`)
remove send ?

2018-11-20 12:51 UTC, picollomartin requested changes

2018-11-20 12:51 UTC, mpicollo-wolox commented on app/controllers/users.js
> +    const signErrors = validateUser(user, ['email', 'password']);
Why this validation is here ?

2018-11-20 12:51 UTC, mpicollo-wolox commented on app/controllers/users.js
> +    const signErrors = validateUser(user, ['email', 'password']);
This validation should be in the middleware

2018-11-21 12:33 UTC, picollomartin approved these changes
Check some name of variables/functions, things like `result` or `session` (for a controller function) sometimes are a little tricky to understand

2018-11-21 12:33 UTC, mpicollo-wolox commented on app/routes.js
> +  } = require('./middlewares/signValidations'),
Rename this middleware

2018-11-21 19:48 UTC, merged